# Generated by Django 3.2.7 on 2021-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('residual', models.FloatField()),
                ('trend', models.FloatField()),
                ('seasonal', models.FloatField()),
                ('weights', models.FloatField()),
                ('baseline', models.FloatField()),
                ('score', models.FloatField()),
                ('anomalies', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'STL TimeSeries Analysis',
            },
        ),
    ]
