# Generated by Django 3.2.7 on 2021-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subpub_emulator', '0003_alter_temperature_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Send'), (0, 'Stop')], null=True),
        ),
    ]
