version: '3'

services: 
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: djangotuto
      MYSQL_DATABASE: tutorial
      MYSQL_USER: tuto
      MYSQL_PASSWORD: hellotuto
    ports: 
      - '3306:3306'
    expose:
      - "3306"

  redis:
    image: redis:alpine

  etlservice:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports: 
      - '8000:8000'
    volumes: 
      - .:/app
    depends_on: 
      - db
      - redis
volumes: 
  db_data: